on:
  push:
    branches:
      - release

jobs:
  buildForWindows:
    runs-on: windows-latest
    steps:
      - name: è®¾ç½® Tauri Action
        uses: tauri-apps/tauri-action@v0
      - name: å®‰è£…ä¾èµ–ğŸ“¦
        run: pnpm install
      - name: æ„å»ºğŸ”¨
        run: pnpm run build
