on: push

jobs:
  buildForWindows:
    runs-on: windows-latest
    steps:
      - name: è¯»å–ä»“åº“å†…å®¹ğŸ¤”
      - uses: actions/checkout@v4
      - uses: tauri-apps/tauri-action@v0
      - name: å®‰è£…ä¾èµ–ğŸ“¦
        run: pnpm install
      - name: æ„å»ºğŸ”¨
        run: pnpm run build
